// Generated by Selenium IDE
package org.ual.hmis.equipo11;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestsEliminacionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
	System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modificacionDeTareaCasoBackToList() {
    // Test name: ModificacionDeTarea(CasoBackToList)
    // Step # | name | target | value
    // 1 | open | http://coresqlfernandezcamacho.azurewebsites.net/ | 
    driver.get("http://coresqlfernandezcamacho.azurewebsites.net/");
    // 2 | setWindowSize | 887x570 | 
    driver.manage().window().setSize(new Dimension(887, 570));
    // 3 | storeText | css=tr:nth-child(1) > td:nth-child(1) | Nombre
    vars.put("Nombre", driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText());
    // 4 | storeText | css=tr:nth-child(1) > td:nth-child(2) | Fecha
    vars.put("Fecha", driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText());
    // 5 | click | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[2]/a[normalize-space(text()) = 'Edit'] | 
    driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[2]/a[normalize-space(text()) = \'Edit\']")).click();
    // 6 | click | linkText=Back to List | 
    driver.findElement(By.linkText("Back to List")).click();
    // 7 | assertText | css=tr:nth-child(1) > td:nth-child(1) | ${Nombre}
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).getText(), is("vars.get(\"Nombre\").toString()"));
    // 8 | assertText | css=tr:nth-child(1) > td:nth-child(2) | ${Fecha}
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("vars.get(\"Fecha\").toString()"));
  }
  @Test
  public void eliminacionDeTareaCasoBackToList() {
    // Test name: EliminacionDeTarea(CasoBackToList)
    // Step # | name | target | value
    // 1 | open | http://coresqlfernandezcamacho.azurewebsites.net/ | 
    driver.get("http://coresqlfernandezcamacho.azurewebsites.net/");
    // 2 | setWindowSize | 887x570 | 
    driver.manage().window().setSize(new Dimension(887, 570));
    // 3 | click | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[2]/a[normalize-space(text()) = 'Delete'] | 
    driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[2]/a[normalize-space(text()) = \'Delete\']")).click();
    // 4 | click | linkText=Back to List | 
    driver.findElement(By.linkText("Back to List")).click();
    // 5 | assertText | //td[normalize-space(text()) = 'Tarea1'] | Tarea1
    assertThat(driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']")).getText(), is("Tarea1"));
  }
  @Test
  public void modificacionDeTareaCasoCorrecto() {
    // Test name: ModificacionDeTarea(CasoCorrecto)
    // Step # | name | target | value
    // 1 | open | http://coresqlfernandezcamacho.azurewebsites.net/ | 
    driver.get("http://coresqlfernandezcamacho.azurewebsites.net/");
    // 2 | setWindowSize | 887x661 | 
    driver.manage().window().setSize(new Dimension(887, 661));
    // 3 | storeText | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[1] | Fecha
    vars.put("Fecha", driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[1]")).getText());
    // 4 | click | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[2]/a[normalize-space(text()) = 'Edit'] | 
    driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[2]/a[normalize-space(text()) = \'Edit\']")).click();
    // 5 | click | id=CreatedDate | 
    driver.findElement(By.id("CreatedDate")).click();
    // 6 | type | id=CreatedDate | 2022-04-15
    driver.findElement(By.id("CreatedDate")).sendKeys("2022-04-15");
    // 7 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 8 | assertNotText | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[1] | ${Fecha}
    assertThat(driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[1]")).getText(), is(not("vars.get(\"Fecha\").toString()")));
    // 9 | assertText | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[1] | 2022-04-15
    assertThat(driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[1]")).getText(), is("2022-04-15"));
  }
  @Test
  public void eliminacionDeTareaCasoCorrecto() {
    // Test name: EliminacionDeTarea(CasoCorrecto)
    // Step # | name | target | value
    // 1 | open | http://coresqlfernandezcamacho.azurewebsites.net/ | 
    driver.get("http://coresqlfernandezcamacho.azurewebsites.net/");
    // 2 | setWindowSize | 887x570 | 
    driver.manage().window().setSize(new Dimension(887, 570));
    // 3 | click | //td[normalize-space(text()) = 'Tarea1']/following-sibling::*[2]/a[normalize-space(text()) = 'Delete'] | 
    driver.findElement(By.xpath("//td[normalize-space(text()) = \'Tarea1\']/following-sibling::*[2]/a[normalize-space(text()) = \'Delete\']")).click();
    // 4 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
